services:
  backend:
    build:
      context: ./rubikon-backend
      dockerfile: prod.Dockerfile
    env_file:
      - ./rubikon-backend/.env
    depends_on:
      - db
    volumes:
      - staticfiles:/app/staticfiles
    restart: always

  frontend:
    build: ./rubikon-frontend
    volumes:
      - frontend_dist:/app/dist
    depends_on:
      - backend
    restart: "no"

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./rubikon-backend/.env
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - staticfiles:/app/staticfiles:ro
      - frontend_dist:/frontend:ro
      - media:/app/media:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  postgres_data:
  staticfiles:
  frontend_dist:
